name: CI/CD - API REST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Tests y Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar dependencias
        run: dotnet restore WebApp.Tests/WebApp.Tests.csproj

      - name: Ejecutar pruebas con coverage
        run: |
          dotnet test WebApp.Tests/WebApp.Tests.csproj \
            --collect:"XPlat Code Coverage" \
            --settings coverage.runsettings

      - name: Mostrar coverage
        run: |
          echo "===== RESULTADO DE COVERAGE ====="
          grep -o 'line-rate="[^"]*"' \
            WebApp.Tests/TestResults/*/coverage.cobertura.xml | head -1


  docker:
    name: Build y Push Docker
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagen
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            monteswastaken/practica-devops-api:latest
            monteswastaken/practica-devops-api:sha-${{ github.sha }}
